MelbourneHighSchoolRobotics/ev3sim

README.md
docs/customisation.rst
docs/ev3_extensions.rst
docs/setup.rst
setup.py

Fix change to MHSRobotics.

---

.github/workflows/docs_deploy.yml

https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-add-cname-file-cname

Add cname to github pages deploy

---

ev3sim/presets/pause_interactor.py
ev3sim/presets/soccer.yaml
ev3sim/visual/objects.py

Didn't manage to get the click event working, couldn't figure out how the colliders masks were organised.

Pause Interactions

---

ev3sim/devices/ultrasonic/base.py
ev3sim/objects/base.py
ev3sim/presets/pause_interactor.py
ev3sim/presets/pick_up_interactor.py
ev3sim/presets/soccer.py
ev3sim/presets/soccer.yaml
ev3sim/visual/objects.py

This separates objects based on whether they are static/dynamic, although there's at least 32 categories we can use if we want.
For now the pick up interactor can move any *dynamic* object, while the pause interactor will check every *static* object.

Object Masking

---

docs/setup.rst

Thanks for pointing out this mistake @platy11

fix incorrect arch installation instructions

---

ev3sim/attach.py
ev3sim/simulation/communication.py
ev3sim/single_run.py
ev3sim/visual/manager.py
ev3sim/visual/objects.py

Fixes #55 .
Was a lat more painful than I was expecting, turns out that the attach script was also silently raises a Deadline exception, which needed to be handled separately.
Also added support for dynamic resizing of the window, which while technically functional doesn't handle a few of the objects in our soccer preset to nicely (Try it out for yourself to get an idea of this)

Bug window move

---

ev3sim/attach.py

Add invoking folder to mocked path for attach scripts.

---

docs/ev3_extensions.rst
ev3sim/attach.py
ev3sim/code_helpers.py
ev3sim/robots/demo.py
setup.py

Adds a code helper to wait for tick (https://github.com/MelbourneHighSchoolRobotics/ev3sim/issues/91)

Wait for tick

---

ev3sim/attach.py
setup.py

@peter-drew please check locally as I might just be too fast to notice the difference. This should hopefully fix the issues however.

Ensure `wait_for_tick` also waits for writes to occur.

---

.github/workflows/docs_check.yml
.github/workflows/python_test.yml

Doesn't seem to be working properly anyway

remove pull_request_target from actions

---

docs/customisation.rst
docs/ev3_extensions.rst

Fixes #108 . Thanks @peter-drew for reminding me as I'd completely forgot to include some in the original PR.

Button event docs

---

ev3sim/robot.py
ev3sim/simulation/communication.py
setup.py

Ensure event queue is instantiated regardless of attached code.

---

ev3sim/devices/infrared/base.py

Fixes #116 .
Has also illuminated another issue though - we don't wait for new values after mode changes, which means values can be out of date.

Update IR to support all valid modes.

---

ev3sim/attach.py

Fixes #120 . Also shouldn't cause any slowdown of scripts but I'd recommend someone tries the demo script in addition to myself before approving.

Make reads blocking if mode change occured on same tick.

---

ev3sim/presets/soccer.py
ev3sim/presets/soccer.yaml

Resolves #124 .
Also moved these settings above visual elements for clarity.
Worth noting this needs to be rethought for an overhaul regardless, settings in presets is not very accessible.

Using settings instead of kwargs for soccer.py

---

.github/workflows/pypi_release.yml

closes #134 , should replace #137

change release hook to on release:released

---

docs/batched_commands.rst
docs/customisation.rst
ev3sim/batched_commands/communications_demo.yaml
ev3sim/batched_commands/soccer_competition.yaml
ev3sim/batched_run.py
ev3sim/presets/soccer.yaml
ev3sim/simulation/loader.py
ev3sim/single_run.py
ev3sim/visual/manager.py
ev3sim/visual/objects.py
ev3sim/visual/utils.py

Add settings on batch, remove loader and screen settings.

---

ev3sim/presets/soccer.yaml
ev3sim/presets/soccer_random.yaml

Adjust constants

---

ev3sim/single_run.py
ev3sim/visual/manager.py
requirements.txt

Add new version notification to pygame window and program startup.

---

ev3sim/presets/soccer.py

Ensure ball spawn position is unblocked if possible.

---

docs/ev3_extensions.rst

I forgot about docs for the new addition :/
no need to rerelease, docs will rebuild anyways.

Add some documentation for robot_id

---

docs/batched_commands.rst
docs/customisation.rst
ev3sim/batched_commands/communications_demo.yaml
ev3sim/batched_commands/soccer_competition.yaml
ev3sim/presets/soccer.yaml
ev3sim/presets/soccer_random.yaml
ev3sim/visual/manager.py
ev3sim/visual/objects.py
ev3sim/visual/utils.py

Does a few things:
- Ensures aspect ratio is maintained after resizing window
- Changes default window size to 960x720 (Fixes #172 )
- Smooths out text and image scaling

Screen scaling

---

ev3sim/batched_run.py
ev3sim/presets/rescue.py
ev3sim/presets/soccer.py
ev3sim/robot.py
ev3sim/simulation/loader.py

Decouples the connection between starting a batch run and starting the code processes. This allows us to manually reset the code running on bots as a feature going into the future.

Attach decoupling

---

ev3sim/examples/robots/bot.bot
ev3sim/examples/robots/communication_client.bot
ev3sim/examples/robots/communication_server.bot
ev3sim/examples/robots/controllable.bot
ev3sim/examples/robots/rescue_bot.bot
ev3sim/examples/sims/communications_demo.sim
ev3sim/presets/soccer_random.yaml
ev3sim/validation/batch_files.py
ev3sim/validation/bot_files.py
ev3sim/validation/preset_files.py
ev3sim/visual/menus/batch_select.py
ev3sim/visual/menus/bot_menu.py

Just allows custom presets to be defined in a way that does not clutter the main gui.
This means we can define some niche presets, put them in a student's workspace, and batch files can still recognise this preset.

Custom presets

---

ev3sim/gui.py

Just makes sure you can definitely run the application on school network.
Fixes #200

Try/Except the new version check.

---

ev3sim/visual/menus/workspace_menu.py

Removes the redundant skip button from workspace selector.
Fixes #201

Remove workspace menu skip button.

---

ev3sim/gui.py
requirements.txt

Have created a personal sentry org that the sim reports to.
Chuck me your email if you wanted to be added to the org, I should just be able to handle the reports though.

Add sentry to the project.

---

ev3sim/visual/menus/base_menu.py
ev3sim/visual/menus/batch_select.py
ev3sim/visual/menus/bot_menu.py

Just adds a few error messages to catch invalid bot/sim files, to give a bit more information to users (and us) about what's broken.

Fault tolerance

---

ev3sim/updates.py

If workspace was not defined then you got a crash. Fixes this.

Ensure checking for an update to the bot definitions does not crash sim.

---

ev3sim/batched_run.py
ev3sim/gui.py
ev3sim/search_locations.py

Allows custom presets to be loaded in the new workspace format.

Custom fix

---

.all-contributorsrc

Following suggestions from @angustrau , reorders the list of contributors in the README.

Modify contributors list.

---

ev3sim/presets/default_config.yaml
ev3sim/visual/animation_utils.py
ev3sim/visual/manager.py
ev3sim/visual/menus/base_menu.py
ev3sim/visual/menus/main.py
ev3sim/visual/settings/main_settings.py

@jtbui20 see the changes in this PR, merge if you are happy and start working on the `ui_version_2` branch.
Example use can be found in visual/menus/main.py, all animation functionality is in base_menu.py.

Animations

---

ev3sim/devices/base.py
ev3sim/devices/button/base.py
ev3sim/devices/colour/ev3.py
ev3sim/devices/compass/ev3.py
ev3sim/devices/motor/base.py
ev3sim/devices/ultrasonic/ev3.py
ev3sim/robot.py
ev3sim/simulation/interactor.py

More of a bugfix than anything. Don't think this needs review.

Ensure restarted bots have no velocity or incorrect device values.

---

build_exe.py
config-no-admin.nsi
config.nsi
executable_entry.spec

Removes that annoying prompt on open and is good all round.
Has been tested in updating and a fresh install locally, although testing from school computers from other users would be appreciated.

Remove Admin privileges to ev3sim.exe

---

ev3sim/simulation/interactor.py

Just a simple change that ensures any messages that are not interactors requesting input are removed.

Also remove static and temporary console messages on bot restart.

---

ev3sim/attach_bot.py

Should fix any issues encountered @angustrau

Mock ev3dev2 interfaces that are not implemented by the simulator.

---

ev3sim/simulation/loader.py

Ensure the actual output is used in request message.

---

config-no-admin.nsi
config.nsi
ev3sim/gui.py
ev3sim/updates.py
ev3sim/visual/manager.py
ev3sim/visual/menus/batch_select.py
ev3sim/visual/menus/main.py
ev3sim/visual/menus/update_dialog.py
requirements.txt

Custom overhaul

---

ev3sim/attach_bot.py
ev3sim/file_helper.py
ev3sim/gui.py
ev3sim/simulation/loader.py
ev3sim/visual/manager.py
ev3sim/visual/menus/bot_menu.py
ev3sim/visual/menus/main.py

Fixes problems with students malforming their workspace path (About 70% of sentry crashes)
Makes certain problems with bots do more than just error out, shows an error window.
Overall a bit safer than previous versions.

More error handling.

---

ev3sim/entry.py

Woops, no wonder I didn't get any errors yesterday!

Ensure unhandled exceptions are reported to sentry.

---

ev3sim/attach_bot.py

Just a change for some of the custom tasks I'm making.

Ensure no input message is printed when message=None.

---

ev3sim/file_helper.py

@angustrau Can you try running ev3sim locally with this? Try using / and \ in the filepaths, because I know I something similar to this originally but it wasn't loading files correctly.
For the use case we were looking at on Thursday, you'll want `allowed_areas = ['local|/home/...']`

Write find_abs in a sane way.
