ev3sim/attach.py, ev3sim/file_helper.py, setup.py
Some of these errors crept in when I moved everything into the `ev3` folder - I forgot to check the `attach` script.
This also ensures that the file helper will correctly look into relative locations when specified.
=> Attach fixes

MANIFEST.in, ev3sim/file_helper.py, ev3sim/visual/objects.py
Just a quick fix so the font loading works when ev3sim is installed as a package.
=> Ensure file handling is done for font files, include in package.

MANIFEST.in
Use the correct form of slash to separate directories in line with https://packaging.python.org/guides/using-manifest-in/.
Thanks @platy11 for bringing this to attention!
=> Use correct slash on Manifest file.

LICENSE, ev3sim/attach.py, ev3sim/batched_run.py, ev3sim/sim.py, ev3sim/simulation/communication.py, ev3sim/single_run.py
This PR:
- sets `ev3sim` to only bind to localhost (::1) by default
- adds flags (`--simulator_addr` for `ev3attach` and `--bind_addr` for `ev3sim`) to allow users to listen on all interfaces or use a different port if they want to for whatever reason
Note that this PR targets main, but was based on batched_commands so should be merged after #53. 
I haven't tested this on Windows yet, presumably it works but it would be best to check.
=> Bind only to localhost by default

setup.py
pip installing currently fails on `main` because of the emojis added by all-contributors yesterday.
=> Fix setup.py to allow for emoji in the README.md

ev3sim/attach.py
Very simple PR - last PR we mocked print to send information to the simulator, but this also mocks print on the main thread 🤦 , so if we print an error for example this fails.
So we need to check whether we are on the main thread, and just do builtin prints if this is the case.
=> Fix attach print error on main thread.

ev3sim/devices/motor/base.py
Fixes #98 .
Tested locally with MoveSteering, no longer any errors. Thanks @platy11 for the issue.
=> Add a reset command to motors.

ev3sim/single_run.py
Allows for presets to change class constants and other things with mocking.
To test, try adding the following to `ev3sim/presets/soccer.yaml`:
```
settings:
ev3sim.presets.soccer.SoccerInteractor.GOAL_SCORE_PAUSE_DELAY: 10
```
This will make the delay after soccer goals are scored be 10.
This is the change that will allow specific randomisation constants to be changed via preset @peter-drew, and also after merging this I'll probably remove the command line flag for turning on/off randomisation, we'll instead have to presets, soccer (default) and soccer_randomised.
=> Add option to mock specific values in presets.

.github/workflows/python_lint.yml
Resolves  #118 .
@peter-drew I've made it so the linting only uses python 3.x. I think this is better because I don't really see any reason to lint with a lower version, in fact that could cause some problems down the line (If linting for 3.7 goes one way but for 3.x goes another way, due to some change in style)
=> Separate lint and test workflows.

ev3sim/simulation/communication.py
Currently prints can interrupt eachother, which looks ugly.
This change ensures each print is handled separately, and stdout is flushed before a new print is started.
=> Add a print lock and flush stdout in communications thread.

ev3sim/simulation/communication.py
Fixes errors raised earlier by Zeyang.
=> Ensure only one lock is created per robot.

ev3sim/presets/soccer.yaml
Extends the collider which generates the out on white ruling when the bot leaves. You can visualise this change by making the `fill` of `centreField` object to '#ff0000' in `soccer.yaml`.
=> Modify out on white collider for bots.

ev3sim/visual/menus/base_menu.py, ev3sim/visual/menus/bot_edit.py, ev3sim/visual/menus/rescue_edit.py
Fixes #205 . Just makes it so that other buttons (Such as Save/Cancel) can't be interacted with when a dialog is opened, which will likely mitigate many of the bugs encountered so far.
Has been tested locally, everything seems to work as intended.
=> Dialog fix

ev3sim/visual/menus/base_menu.py, ev3sim/visual/menus/workspace_menu.py, ev3sim/visual/settings/elements.py
Fixes #218
Is a bit clunkier but has been tested and works (and should also work on Mac, as Tk was the thing causing mac errors. Avoiding these file dialogs has ev3sim work fine on mac.
=> Use pygame_gui filepicker dialog rather than tkinter for mac support.

ev3sim/visual/menus/workspace_menu.py, ev3sim/visual/settings/elements.py
Previously we just used the tkinter file dialog for file/directory selecting. Sadly this isn't supported by Mac, and so we had to add pygame_gui's file selector as part of #224 (This is because Mac pygame uses tkinter as the backend, where as windows uses SDL2).
The tkinter dialog is superior and less buggy however, so we should revert this change for windows clients.
=> Revert to tkinter file dialog if on windows.

ev3sim/file_helper.py, ev3sim/gui.py, ev3sim/presets/default_launch.json, ev3sim/simulation/loader.py, ev3sim/updates.py, requirements.txt
This adds support for debugging robots in VS Code. The debugger is automatically launched on port `15995`. To use it just add this to `.vscode/launch.json` 
```
{
"version": "0.2.0",
"configurations": [
{
"name": "Python: Attach to EV3Sim",
"type": "python",
"request": "attach",
"connect": {
"host": "localhost",
"port": 15995
}
}
]
}
```
There's also a new flag `--no-debug` to disable launching the debugger as it can potentially be exploited by a malicious bot. A possible enhancement could be to create `launch.json` automatically if it doesn't exist, but I'm not sure where to do that.
=> Add support for debugging robots

ev3sim/updates.py
Silly bug introduced in 2.1.7 which would mean ev3sim auto crashes on install if you are not upgrading from a previous version 🤦
=> Ensure workspace check is made before attempting to fill it.

.github/workflows/windows_package_create.yml
Disable for now as it hasn't been updated to the new Windows packaging and is causing errors
=> Fix windows CI error

requirements.txt
Set static versions of dependencies to allow for better reproducibility. Maybe we can look into tools like poetry or pipenv later for even more consistency. This will be required for the Nix build PR #289 .
=> Freeze requirements versions

ev3sim/entry.py, ev3sim/file_helper.py, ev3sim/search_locations.py, flake.lock, flake.nix, nix/linux.nix
Moved data to platform native locations with the `platform` placeholder. Only linux supports these locations for now, and this is a no-op on windows and mac. This gets the linux packaged version all the way up to the main menu. Next thing to tackle is the soccer/rescue preset sim files needing to be writeable.
=>  Add platform folders support to search paths 
